# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Set npm cache path
      run: npm config set cache /home/ubuntu/.npm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: portfolio-app/client/package-lock 
    - run: |
        cd portfolio-app
        cd client
        npm install
        npm run build
    - run: |
        cd portfolio-app
        cd server
        npm install

    - run : |
        cd portfoil-app
        cd server
        pm2 start App.js --name=server
        # - run: pm2 restart server
   
